Update 分布编译.yml

diff --git a/.github/workflows/分布编译.yml b/.github/workflows/分布编译.yml
--- a/.github/workflows/分布编译.yml
+++ b/.github/workflows/分布编译.yml
@@ -1,4 +1,4 @@
-name: 分布编译OpenWrt
+name: 分布式编译OpenWrt
 
 on:
   repository_dispatch:
@@ -15,7 +15,7 @@ env:
   UPLOAD_FIRMWARE: true
   UPLOAD_COWTRANSFER: false
   UPLOAD_WETRANSFER: false
-  UPLOAD_RELEASE: true
+  UPLOAD_RELEASE: false
   TZ: Asia/Shanghai
 
 jobs:
@@ -189,27 +189,105 @@ jobs:
       id: compile
       run: |
         echo -e "$(nproc) thread compile"
-        total_threads=$(nproc)
-        threads_per_part=$((total_threads / 2))
-        make -j$threads_per_part || make -j1 V=s
+        if [ "${{ matrix.part }}" = "1" ]; then
+          make -j$(nproc) || make -j1 V=s || { echo "Compile failed at part 1"; exit 1; }
+        elif [ "${{ matrix.part }}" = "2" ]; then
+          make -j$(($(nproc) / 2)) || make -j1 V=s || { echo "Compile failed at part 2"; exit 1; }
+        fi
         echo "status=success" >> $GITHUB_OUTPUT
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
-        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
     - name: Check space usage
-      if: (!cancelled())
+      if: always()
       run: df -hT
 
-    - name: Upload firmware to Releases
-      if: env.UPLOAD_RELEASE == 'true'
-      uses: softprops/action-gh-release@v1
+    - name: Upload bin directory
+      uses: actions/upload-artifact@main
+      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
       with:
-        tag: ${{ github.ref }}
-        files: |
-          openwrt/bin/targets/*/*/*.bin
-          openwrt/bin/targets/*/*/*.img
-          openwrt/bin/targets/*/*/*.gz
-          openwrt/bin/targets/*/*/*.ipk
+        name: OpenWrt_bin_${{ matrix.part }}
+        path: openwrt/bin
+
+    - name: Organize files
+      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled() && !failure() && matrix.part == 2
+      run: |
+        cd openwrt/bin/targets/*/*
+        rm -rf packages
+        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+        echo "status=success" >> $GITHUB_OUTPUT
+
+    - name: Upload firmware directory
+      uses: actions/upload-artifact@main
+      if: steps.organize.outputs.status == 'success' && !cancelled() && matrix.part == 2
+      with:
+        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+        path: ${{ env.FIRMWARE }}
+
+  upload:
+    needs: build
+    runs-on: ubuntu-22.04
+    if: always()
+    
+    steps:
+    - name: Download firmware
+      uses: actions/download-artifact@v3
+      with:
+        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+        path: firmware
+
+    - name: Upload firmware to cowtransfer
+      id: cowtransfer
+      if: env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
+      run: |
+        curl -fsSL git.io/file-transfer | sh
+        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
+        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
+        echo "url=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
+
+    - name: Upload firmware to WeTransfer
+      id: wetransfer
+      if: env.UPLOAD_WETRANSFER == 'true' && !cancelled()
+      run: |
+        curl -fsSL git.io/file-transfer | sh
+        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
+        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
+        echo "url=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
+
+    - name: Generate release tag
+      id: tag
+      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      run: |
+        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
+        touch release.txt
+        [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
+        [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
+        echo "status=success" >> $GITHUB_OUTPUT
+
+    - name: Upload firmware to release
+      uses: softprops/action-gh-release@v1
+      if: steps.tag.outputs.status == 'success' && !cancelled()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        tag_name: ${{ steps.tag.outputs.release_tag }}
+        body_path: release.txt
+        files: firmware/*
+
+  cleanup:
+    needs: [build, upload]
+    if: always()
+    runs-on: ubuntu-22.04
+    
+    steps:
+    - name: Delete workflow runs
+      uses: Mattraks/delete-workflow-runs@v2
+      with:
+        retain_days: 1
+        keep_minimum_runs: 3
+
+    - name: Remove old Releases
+      uses: dev-drprasad/delete-older-releases@v0.1.0
+      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+      with:
+        keep_latest: 3
+        delete_tags: true
+      env:
